### ISSUE TITLE
I want to use song URL instead of id to link songs.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cachecleanerjeet/JiosaavnAPI#1]
Will look into this code and will do changes for jiosaavn.ga when I'm free. also will rewrite UI for my site. Nice Work. Great.

**Comment by ParveenBhadooOfficial** [comment]
as we're deploying in CF, will it face problems like song not available in specific countries like in that python api?

**Comment by cachecleanerjeet** [comment]
song url is also supported 
https://jiosaavn-api.vercel.app/link?query=https://www.jiosaavn.com/song/makhna/GAcfdEEJfHY

i suggest vercel insted of using cloudflare,. i created anothe repo for [serverless jiosaavn api](https://jiosaavn-api.vercel.app/link?query=https://www.jiosaavn.com/song/makhna/GAcfdEEJfHY
)

**Comment by cachecleanerjeet** [comment]
i don't think contry is 

> as we're deploying in CF, will it face problems like song not available in specific countries like in that python api?

Nope. Previously my server was aws singapore, i never got an issue. Now i use vercel's serverless function it will connect with a nearest vercel's server.
Song availability issue is caused by inpresence of media preview url
