### ISSUE TITLE
Can u make it compatible with cyberboy project

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cachecleanerjeet/JiosaavnAPI#4]
does the json for songs same as for https://github.com/cyberboysumanjay/JioSaavnAPI

i don't want to edit bhadoomusic.com and just want to use this api using AWS Serverless.

**Comment by cachecleanerjeet** [comment]
musicder.net is using the api serverlessly using CF Worker. Right now it is cors protected but can explore it [here](https://api.musicder.net) . And I can make the endpoints and responses looks like with sumanjay's jiosaavn api.  But can't do that in this repo, because many people are using my api.

**Comment by ParveenBhadooOfficial** [comment]
if possible. fork the repo and do please. will host on AWS Mumbai server for public use.

**Comment by ParveenBhadooOfficial** [comment]
Anything possible in AWS which doesn't just stops. Python app crashes very often.

**Comment by cachecleanerjeet** [comment]
Oki,
